CONFIG_CRYPTO=y
CONFIG_CRYPTO_MBEDTLS_SHIM=y


CONFIG_MBEDTLS=y
CONFIG_MBEDTLS_ENABLE_HEAP=y
CONFIG_MBEDTLS_HEAP_SIZE=2048
#CONFIG_MBEDTLS_BUILTIN=y
#CONFIG_MBEDTLS_CIPHER=y
#CONFIG_MBEDTLS_AES_C=y
#CONFIG_MBEDTLS_CIPHER_MODE_CBC=y

CONFIG_MAIN_STACK_SIZE=4096
# CONFIG_VCML_SIMDEV=y
CONFIG_KERNEL_VM_SIZE=0x80000000
CONFIG_MINIMAL_LIBC=y
CONFIG_MINIMAL_LIBC_OPTIMIZE_STRING_FOR_SIZE=n

# this flag forces the compiler to insert stack 
# canary checks into functions, routing overflows 
# directly to the same __stack_chk_fail symbol.
CONFIG_STACK_CANARIES=y


CONFIG_SERIAL=y
CONFIG_UART_PYDROFOIL=y
CONFIG_SYS_CLOCK_EXISTS=y
CONFIG_LOG=y
CONFIG_LOG_MODE_MINIMAL=y
CONFIG_RISCV_PMP=n
# CONFIG_PLIC=n
CONFIG_PLIC=n
CONFIG_MULTI_LEVEL_INTERRUPTS=n
# --- MULTICORE SMP SETTINGS ---
CONFIG_SMP=y
CONFIG_MP_MAX_NUM_CPUS=1
# Optional but highly recommended for debugging:
# This lets you see which core is running which thread
CONFIG_THREAD_NAME=y
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_FPU=n
CONFIG_RISCV_MACHINE_TIMER=y
# CONFIG_DEBUG_INFO=n
# CONFIG_SPIN_VALIDATE=y
# CONFIG_ASSERT=y
